path:
  ckpt_path: "./output/ckpt/cmltts_entoa_prossegue"
  log_path: "./output/log/cmltts_entoa_prossegue"
  result_path: "./output/result/cmltts_entoa_prossegue"
optimizer:
  batch_size: 16 
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 3000
  anneal_steps: [200000, 300000, 600000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 500
  synth_step: 1000
  val_step: 5000
  save_step: 10000
